pipelines:
  default:
    - step:
        name: Unit Tests
        image: python:3.7
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - set +e
          - coverage run --source=hw1 -m unittest discover -s hw1/ -p "*_test.py"
          - coverage report
          - python main.py | diff output.txt -
