version: '3'
services:
  flask:
    container_name: flask-docker
    build:
      context: .
      dockerfile: Dockerfile
    image: main-flask
    depends_on:
      - "redis"
    ports:
      - "5000:5000"
    networks:
      - redis-net
  redis:
    container_name: redis-docker
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - redis-net
  jobs:
    container_name: jobs-docker
    build:
      context: ./
      dockerfile: Docker-jobs
    image: main-jobs
    depends_on:
      - "redis"
      - "flask"
    networks:
      - redis-net
networks:
  redis-net:
